version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlaubsantrag-app-prod
    restart: unless-stopped

    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/production.db
      JWT_SECRET: ihr-super-geheimer-jwt-schluessel-2024
      DB_TYPE: sqlite
      PORT: "3001"
      ALLOWED_ORIGIN: "https://urlaub.myfire.cloud"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
    driver: local