version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlaubsantrag-app-prod
    restart: unless-stopped

    environment:
      NODE_ENV: production
      DB_TYPE: ${DB_TYPE:-postgres}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-3001}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    volumes:
      - sqlite_data:/app/data
    networks:
      - kk4c08g4oso4cgokwkskskww
      - coolify

volumes:
  sqlite_data:
    driver: local

networks:
  kk4c08g4oso4cgokwkskskww:
    external: true
  coolify:
    external: true