version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlaubsantrag-app-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/app/data/production.db
      JWT_SECRET: your-super-secret-jwt-key-2024-production
      DB_TYPE: sqlite
    ports:
      - "3001:3000"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
    driver: local