# Änderung: Single-Service Docker Compose für SQLite
# Grund: Einfacheres Deployment, persistente SQLite-Datenbank über Volume

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlaubsantrag-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_TYPE: ${DB_TYPE:-postgres}
      JWT_SECRET: ${JWT_SECRET:-ihr-super-geheimer-jwt-schluessel-2024}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      # Änderung: SQLite-Datenbank persistent speichern
      # Grund: Daten bleiben bei Container-Neustarts erhalten
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local